version: '2'
services:
  web:
    image: whyour/qinglong:latest
    volumes:
      - ./data/config:/ql/config
      - ./data/log:/ql/log
      - ./data/db:/ql/db
      - ./data/scripts:/ql/scripts
      - ./data/repo:/ql/repo
    environment:
      - ENABLE_HANGUP=true
      - ENABLE_WEB_PANEL=true
    networks: 
      - internal
    restart: always

  nginx:
    image: nginx:alpine
    volumes: 
      - ./docker/services/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "0.0.0.0:5700:80"
    networks: 
      - internal
    restart: always

networks: 
  internal: