version: '2'
services:
  web:
    # alpine 基础镜像版本
    image: whyour/qinglong:latest
    # debian-slim 基础镜像版本
    # image: whyour/qinglong:debian  
    volumes:
      - ./data:/ql/data
    environment:
      # 部署路径非必须，以斜杠开头和结尾，比如 /test/
      QlBaseUrl: '/'
    networks: 
      - internal
    restart: always

  nginx:
    image: nginx:alpine
    volumes: 
      - ./docker/services/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "0.0.0.0:5700:80"
    networks: 
      - internal
    restart: always

networks: 
  internal:
